### ISSUE TITLE
Çevrilmemiş bölüm başlıkları

### ISSUE THREAD

**Issue by setanarut** [RustDili/Rust-Ogrenmek#4]
Orjinal kaynakta bölüm başlıkları konuya göre, çeviride ise Birinci İkinci Üçüncü şeklinde çevrilmiş. Düzeltilmesi gerek.

**Comment by RustDili** [comment]
Merhaba,
Bölüm başlıklarının birebir aynı olması gerekmiyor. Önerinizi bu repoyu mdbook biçiminde yayınlarken gözden geçireceğim.
Desteğiniz için teşekkür eder iyi çalışmalar dilerim.

**Comment by setanarut** [comment]
> Merhaba, Bölüm başlıklarının birebir aynı olması gerekmiyor. Önerinizi bu repoyu mdbook biçiminde yayınlarken gözden geçireceğim. Desteğiniz için teşekkür eder iyi çalışmalar dilerim.

Nasıl gerekmiyor? bu nasıl bir savunma anlamadım. Ben çatalımda düzelttim siz bu kafada devam edin.

**Comment by RustDili** [comment]
Bu zihniyet için üretmiyoruz!
Saygılı olun!
